/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("use.implementation.java-library-conventions")
}

dependencies {
   implementation("com.squareup.okhttp3:okhttp:4.10.0")
//    api("com.squareup.okhttp3:okhttp:4.10.0")
}