/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package use.implementation.app;

import use.implementation.list.LinkedList;

import static use.implementation.utilities.StringUtils.join;
import static use.implementation.utilities.StringUtils.split;
import static use.implementation.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
