/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.juhyung.study.netty.app;

import dev.juhyung.study.netty.list.LinkedList;

import static dev.juhyung.study.netty.utilities.StringUtils.join;
import static dev.juhyung.study.netty.utilities.StringUtils.split;
import static dev.juhyung.study.netty.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
