/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("dev.juhyung.study.netty.java-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))
    implementation("io.netty:netty-all:4.1.70.Final")
    implementation("org.xerial:sqlite-jdbc:3.36.0.3")
}

application {
    // Define the main class for the application.
//    mainClass.set("dev.juhyung.study.netty.app.App")
    project.logger.info("chooseMain is " + project.findProperty("chooseMain"));
    mainClass.set(project.findProperty("chooseMain").toString());
}
