/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("dev.juhyung.study.netty.java-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))
    implementation("io.netty:netty-all:4.1.70.Final")
}

application {
    // Define the main class for the application.
    mainClass.set("dev.juhyung.study.netty.app.App")
}
